name: CI/CD Build, Push & Deploy for ecommerce-app

on:
  push:
    paths:
      - 'backend/**'
    branches: [ "feature" ]

permissions:
  contents: read
  issues: write
  pull-requests: write
  security-events: write

env:
  REGISTRY: gcr.io
  PROJECT: devops-docker-491007
  APP: ecommerce-backend

jobs:
  # sonar-analysis:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: SonarQube Scan
  #       uses: SonarSource/sonarqube-scan-action@v2
  #       with:
  #         args: >
  #           -Dsonar.projectKey=ecommerce-backend
  #           -Dsonar.sources=backend
  #           -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
  #           -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  #     - name: SonarQube Quality Gate
  #       uses: SonarSource/sonarqube-quality-gate-action@v1
  #       timeout-minutes: 5
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-push:
    #needs: sonar-analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_DEVOPS_CREDENTIALS }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build Image
        run: |
          docker build backend \
          -f backend/Dockerfile \
          -t $REGISTRY/$PROJECT/$APP:${{ github.run_number }}
          
      # Download template
      - name: Download Trivy HTML template
        run: curl -L https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -o html.tpl

      - name: Trivy Scan 
        uses: aquasecurity/trivy-action@master 
        continue-on-error: true
        with: 
          image-ref: ${{ env.REGISTRY }}/${{ env.PROJECT }}/${{ env.APP }}:${{ github.run_number }}
          format: template 
          template: "@html.tpl" 
          output: trivy-report.html
          severity: CRITICAL,HIGH 

      - name: Upload Trivy Report 
        uses: actions/upload-artifact@v4 
        with: 
          name: trivy-html-report 
          path: trivy-report.html

      - name: Push Image
        run: |
          docker push $REGISTRY/$PROJECT/$APP:${{ github.run_number }}


      - name: Checkout Helm repo
        uses: actions/checkout@v3
        with:
          repository: charanya310/helmcharts
          token: ${{ secrets.GIT_TOKEN }}

      - name: Update Helm values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'ecomm-backend/values.yaml'
          repository: charanya310/helmcharts
          token: ${{ secrets.GIT_TOKEN }}
          propertyPath: 'image.tag'
          value: ${{ github.run_number }}
          branch: main
          commitChange: true
          createPR: false
          message: "tag update to ${{ github.run_number }}"
