name: CI/CD Build, Push & Deploy for ecommerce-app

on:
  push:
    paths:
      - 'frontend/**'
    branches: [ "feature" ]

env:
  REGISTRY: gcr.io
  PROJECT: devops-docker-491007
  APP: ecommerce-frontend

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.projectKey=ecommerce-frontend
            -Dsonar.sources=frontend
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-push:
    needs: sonar-analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_DEVOPS_CREDENTIALS }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build Image
        run: |
          docker build frontend \
          -f frontend/Dockerfile \
          -t $REGISTRY/$PROJECT/$APP:$GITHUB_RUN_NUMBER

      - name: Push Image
        run: |
          docker push $REGISTRY/$PROJECT/$APP:$GITHUB_RUN_NUMBER


  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to VM
        env:
          VM_HOST: ${{ secrets.VM_SSH_HOST }}
          VM_USER: ${{ secrets.VM_SSH_USER }}
          VM_PORT: ${{ secrets.VM_SSH_PORT }}
        run: |
          ssh -o StrictHostKeyChecking=no -p $VM_PORT $VM_USER@$VM_HOST << EOF
          sudo gcloud auth configure-docker --quiet
          sudo docker pull gcr.io/devops-docker-491007/ecommerce-frontend:$GITHUB_RUN_NUMBER
          sudo docker stop frontend || true
          sudo docker rm frontend || true
          sudo docker run -d -p 3000:3000 --name frontend gcr.io/devops-docker-491007/ecommerce-frontend:$GITHUB_RUN_NUMBER
          EOF